networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/r/tuxgasy/dolibarr
  dolibarr:

    # image, build, depends_on, command
    image: tuxgasy/dolibarr:17.0.2
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.dolibarr.rule=Host(`dolibarr.mein-reverseproxy.de`)
      - traefik.http.services.dolibarr.loadbalancer.server.port=80

      # homepage
      - homepage.weight=-999
      - homepage.group=dolibarr
      - homepage.name=dolibarr
      - homepage.description=tuxgasy/dolibarr:17.0.2
      - homepage.icon=dolibarr.png
      - homepage.href=https://dolibarr.mein-reverseproxy.de
      - homepage.ping=https://dolibarr.mein-reverseproxy.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/dolibarr/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

    # healthcheck, restart
    healthcheck:
      test: curl -s --fail http://localhost
    restart: unless-stopped


  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    image: mariadb:11.0.3-jammy

    # labels
    labels:

      # homepage
      - homepage.weight=-100
      - homepage.group=dolibarr
      - homepage.name=mariadb
      - homepage.description=mariadb:11.0.3-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/mariadb/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/mariadb/mysql:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su=root --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
