networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # link to repos
  servicename:

    # image, build, depends_on, command
    image: imagename:tagname
    build: path
    depends_on:
      - serviceName
    command: command

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.servicename.rule=Host(`servicename.mein-reverseproxy.de`)
      - traefik.http.services.servicename.loadbalancer.server.port=80

      # homepage
      - homepage.group=stackname
      - homepage.name=servicename
      - homepage.description=imagename:tagname
      - homepage.icon=servicename.png
      - homepage.href=https://servicename.mein-reverseproxy.de
      - homepage.ping=https://servicename.mein-reverseproxy.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    container_name: servicename
    hostname: servicename
    networks:
      - default
      - traefik

    # env_file, environment

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # config
      - ./config/a:/etc:ro

      # data
      - ./data/a:/var:cached

    # healthcheck, restart
    healthcheck:
      test: wget -q --spider http://127.0.0.1
    restart: unless-stopped
