services:

  # https://hub.docker.com/r/traefik/whoami
  # https://hub.docker.com/_/alpine/
  whoami:

    image: traefik/whoami-alpine:v1.10.1-3.18.3

    build:
      context: build

      args:

        # https://hub.docker.com/r/traefik/whoami
        - baseRespository=traefik/whoami
        - baseTag=v1.10.1

        # https://hub.docker.com/_/alpine/
        - releaseRepository=alpine
        - releaseTag=3.18.3

      tags:
        - traefik/whoami-alpine:v1.10.1-3.18.3

    volumes:
      - /etc/localtime:/etc/localtime:ro
