networks:
  traefik:
    external: true

services:

  # https://hub.docker.com/r/traefik/whoami
  # https://hub.docker.com/_/alpine/
  whoami:

    # image, restart, build
    image: traefik/whoami-alpine:v1.10.1-3.18.3
    restart: unless-stopped
    build:
      context: build
      args:
        # https://hub.docker.com/r/traefik/whoami
        - baseRespository=traefik/whoami
        - baseTag=v1.10.1
        # https://hub.docker.com/_/alpine/
        - releaseRepository=alpine
        - releaseTag=3.18.3
      tags:
        - traefik/whoami-alpine:v1.10.1-3.18.3

    # container_name, hostname, networks, ports
    container_name: whoami
    hostname: whoami
    networks:
      - traefik

    # env_file, environment

    # volumes
    volumes:
      - /etc/localtime:/etc/localtime:ro

    # healthcheck

    # labels
    labels:
      # traefik
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.mein-reverseproxy.de`)
      # homepage
      - homepage.group=#docker
      - homepage.name=whoami
      - homepage.weight=-800
      - homepage.description=traefik/whoami
      - homepage.showStats=true
      - homepage.icon=traefik.png
      - homepage.href=https://whoami.mein-reverseproxy.de
      - homepage.ping=https://whoami.mein-reverseproxy.de
