# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

background:
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 25 # 0-100

color: neutral

logpath: /app

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  homepage:
    icon: homepage.png
    tab: Containers
    style: row
  pihole:
    icon: pi-hole.png
    tab: Containers
    style: row
  portainer:
    icon: portainer.png
    tab: Containers
    style: row
  traefik:
    icon: traefik.png
    tab: Containers
    style: row
  whoami:
    icon: traefik.png
    tab: Containers
    style: row
  wordpress:
    icon: wordpress.png
    tab: Stacks
    style: row

theme: dark

title: homepage
