services:

  # https://hub.docker.com/r/traefik/whoami
  # https://hub.docker.com/_/alpine/
  whoami:

    depends_on:

      pihole:
        condition: service_healthy

      traefik:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.mein-reverseproxy.de`)
      - traefik.http.services.whoami.loadbalancer.server.port=80

      # homepage
      - homepage.group=#docker
      - homepage.name=whoami
      - homepage.weight=-800
      - homepage.description=traefik/whoami
      - homepage.showStats=true
      - homepage.icon=traefik.png
      - homepage.href=https://whoami.mein-reverseproxy.de
      - homepage.ping=https://whoami.mein-reverseproxy.de
