services:

  # https://hub.docker.com/r/pihole/pihole
  pihole:

    restart: unless-stopped

    networks:
      - traefik

    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8053:8053

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.rule=Host(`pihole.mein-reverseproxy.de`)
      - traefik.http.services.pihole.loadbalancer.server.port=8053

      # homepage
      - homepage.group=#docker
      - homepage.name=pihole
      - homepage.weight=-1000
      - homepage.description=pihole/pihole
      - homepage.showStats=true
      - homepage.icon=pi-hole.png
      - homepage.href=https://pihole.mein-reverseproxy.de/admin
      - homepage.ping=https://pihole.mein-reverseproxy.de/admin
