services:

  # https://hub.docker.com/_/traefik
  traefik:

    depends_on:

      pihole:
        condition: service_healthy
        restart: true

    restart: unless-stopped

    networks:
      - traefik

    ports:
      - 80:80
      - 443:443
      - 8080:8080

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web,websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.mein-reverseproxy.de`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080

      # homepage
      - homepage.group=#docker
      - homepage.name=traefik
      - homepage.weight=-900
      - homepage.description=traefik
      - homepage.showStats=true
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.mein-reverseproxy.de/dashboard
      - homepage.ping=https://traefik.mein-reverseproxy.de/dashboard

      # homepage.widget
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.mein-reverseproxy.de
