networks:
  traefik:
    external: true

services:

  # ghcr.io/benphelps/homepage
  homepage:

    # image, restart, build, command
    image: ghcr.io/benphelps/homepage:v0.6.29
    restart: unless-stopped

    # container_name, hostname, networks, ports
    container_name: homepage
    hostname: homepage
    networks:
      - traefik

    # env_file, environment

    # volumes
    volumes:
      # localtime
      - /etc/localtime:/etc/localtime:ro
      # socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # config
      - ./config/config:/app/config:ro
      - ./config/images:/app/public/images:ro
      # other volumes
      - ./volumes/logs:/app/logs:cached

    # healthcheck

    # labels
    labels:
      # traefik
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.mein-reverseproxy.de`)
      # homepage
      - homepage.group=#docker
      - homepage.name=homepage
      - homepage.description=ghcr.io/benphelps/homepage
      - homepage.showStats=true
      - homepage.icon=homepage.png
      - homepage.href=https://homepage.mein-reverseproxy.de
      - homepage.ping=https://homepage.mein-reverseproxy.de
