networks:

  traefik:
    external: true

services:

  # https://github.com/gethomepage/homepage
  homepage:

    # image, build, depends_on, command
    image: ghcr.io/gethomepage/homepage:v0.8.7

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=internal
      - traefik.http.routers.homepage.rule=Host(`homepage.local.mein-reverseproxy.de`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000

      # homepage
      - homepage.group=homepage
      - homepage.name=homepage
      - homepage.description=ghcr.io/gethomepage/homepage:v0.8.7
      - homepage.ping=https://homepage.local.mein-reverseproxy.de
      - homepage.icon=homepage.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - traefik

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # config
      - ./config/app_config:/app/config
      - ./config/app_public_images:/app/public/images:ro

      # data
      - ./data/app_logs:/app/logs:cached

    # healthcheck, restart
    restart: unless-stopped
