networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/_/nginx
  nginx:

    # image, build, depends_on, command
    image: nginx:1.25-alpine3.18
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`wordpress.mein-reverseproxy.de`)
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      
      # homepage
      - homepage.weight=-999
      - homepage.group=wordpress
      - homepage.name=nginx
      - homepage.description=nginx:1.25-alpine3.18
      - homepage.icon=nginx.png
      - homepage.href=https://wordpress.mein-reverseproxy.de
      - homepage.ping=https://wordpress.mein-reverseproxy.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # volumes
    volumes:
      # localtime
      - /etc/localtime:/etc/localtime:ro
      # config
      - ./config/nginx:/etc/nginx/conf.d:ro
      # other volumes
      - ./data/wordpress:/var/www/html:cached

    # healthcheck, restart
    healthcheck:
      test: curl -s --fail http://localhost
    restart: unless-stopped

  # https://hub.docker.com/_/wordpress
  wordpress:

    # image, build, depends_on, command
    image: wordpress:6.3.0-php8.2-fpm-alpine
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:
      # homepage
      - homepage.weight=-101
      - homepage.group=wordpress
      - homepage.name=wordpress
      - homepage.description=wordpress:6.3.0-php8.2-fpm-alpine
      - homepage.icon=wordpress.png
      - homepage.showStats=true

    # env_file, environment
    env_file:
      - ./config/.env

    # volumes
    volumes:
      # localtime
      - /etc/localtime:/etc/localtime:ro
      # data volumes
      - ./data/wordpress:/var/www/html:cached

    # healthcheck, restart
    healthcheck:
      test: netstat -tnlp | grep fpm -q
    restart: unless-stopped

  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    image: mariadb:11.0.3-jammy

    # labels
    labels:
      # homepage
      - homepage.weight=-100
      - homepage.group=wordpress
      - homepage.name=mariadb
      - homepage.description=mariadb:11.0.3-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/mariadb/.env

    # volumes
    volumes:
      # localtime
      - /etc/localtime:/etc/localtime:ro
      # data volumes
      - ./data/mariadb:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
