networks:
  traefik:
    external: true

services:

  # https://hub.docker.com/r/portainer/portainer-ce
  portainer:

    # image, build, depends_on, command
    image: portainer/portainer-ce:2.19.0-alpine
    command: --admin-password-file /tmp/password

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.mein-reverseproxy.de`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000

      # homepage
      - homepage.group=portainer
      - homepage.name=portainer
      - homepage.description=portainer/portainer-ce:2.19.0-alpine
      - homepage.icon=portainer.png
      - homepage.href=https://portainer.mein-reverseproxy.de
      - homepage.ping=https://portainer.mein-reverseproxy.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - traefik

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock

      # config
      - ./config/password:/tmp/password:ro

      # data
      - ./data/data:/data:cached

    # healthcheck, restart
    healthcheck:
      test: wget -q --spider http://127.0.0.1:9000
    restart: unless-stopped
