networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/r/freshrss/freshrss/
  freshrss:

    # image, build, depends_on, command
    image: freshrss/freshrss:1.21.0-alpine
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`freshrss.mein-reverseproxy.de`)
      - traefik.http.services.freshrss.loadbalancer.server.port=80

      # homepage
      - homepage.weight=-999
      - homepage.group=freshrss
      - homepage.name=freshrss
      - homepage.description=freshrss/freshrss:1.21.0-alpine
      - homepage.icon=freshrss.png
      - homepage.href=https://freshrss.mein-reverseproxy.de
      - homepage.ping=https://freshrss.mein-reverseproxy.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # env_file, environment
    env_file:
      - ./config/freshrss/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/freshrss/data:/var/www/FreshRSS/data:cached
      - ./data/freshrss/extensions:/var/www/FreshRSS/extensions:cached

    # healthcheck, restart
    healthcheck:
      test: (php -r "readfile('http://127.0.0.1/i/');" | grep -q 'jsonVars') || exit 1
    restart: unless-stopped

  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    image: mariadb:11.0.3-jammy

    # labels
    labels:

      # homepage
      - homepage.weight=-100
      - homepage.group=freshrss
      - homepage.name=mariadb
      - homepage.description=mariadb:11.0.3-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/mariadb/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/mariadb/mysql:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
