# HTTP redirect example

http:

  routers:
    google:
      rule: "Host(`google.mein-reverseproxy.de`)"
      service: "traefik@docker"
      middlewares: google

  middlewares:
    google:
      redirectRegex:
        regex: "https://google.mein-reverseproxy.de/(.*)"
        replacement: "https://google.de/${1}"
